services:
  - type: web
    name: taskify-api
    env: docker
    plan: free
    dockerfilePath: ./dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:5000 